# Bench our high-level metadata tree in the core of littlefs

# maximize lookahead buffer, we don't actually gc so we only get one pass
# of the disk for these tests
defines.LOOKAHEAD_SIZE = '(BLOCK_COUNT+8-1) / 8'

[cases.bench_mtree]
# 0 = in-order
# 1 = reversed-order
# 2 = random-order
defines.ORDER = [0, 1, 2]
defines.N = 1024
defines.STEP = 1
defines.SEED = 42
defines.SIZE = 4
in = 'littlefs3/lfs3.c'
code = '''
    lfs3_t lfs3;
    lfs3_format(&lfs3, LFS3_F_RDWR, CFG) => 0;
    lfs3_mount(&lfs3, LFS3_M_RDWR, CFG) => 0;

    // create an mtree with N entries
    uint32_t prng = SEED;
    for (lfs3_size_t i = 0; i < N; i++) {
        lfs3_mid_t i_
                = (ORDER == 0) ? i
                : (ORDER == 1) ? N-1-i
                : BENCH_PRNG(&prng) % N;
        char name[256];
        sprintf(name, "e%05d", i_);
        uint8_t wbuf[SIZE];
        memset(wbuf, 'a'+(BENCH_PRNG(&prng) % 26), SIZE);

        if ((i+1) % STEP == 0) {
            BENCH_START("commit", i+1);
        }
        lfs3_mdir_t mdir;
        lfs3_tag_t tag;
        lfs3_data_t data;
        int err = lfs3_mtree_namelookup(&lfs3,
                0, name, strlen(name),
                &mdir, &tag, &data);
        assert(!err || err == LFS3_ERR_NOENT);
        // new entry?
        if (err == LFS3_ERR_NOENT) {
            lfs3_mdir_commit(&lfs3, &mdir, LFS3_RATTRS(
                    LFS3_RATTR_NAME(
                        LFS3_TAG_REG, +1,
                        0, name, strlen(name)),
                    LFS3_RATTR_BUF(
                        LFS3_TAG_DATA, 0,
                        wbuf, SIZE))) => 0;
            
        // collision?
        } else {
            lfs3_mdir_commit(&lfs3, &mdir, LFS3_RATTRS(
                    LFS3_RATTR_BUF(
                        LFS3_TAG_DATA, 0,
                        wbuf, SIZE))) => 0;
        }
        if ((i+1) % STEP == 0) {
            BENCH_STOP("commit");
        }

        if ((i+1) % STEP == 0) {
            // measure name lookups
            BENCH_START("namelookup", i+1);
            lfs3_mid_t i_ = BENCH_PRNG(&prng) % N;
            sprintf(name, "e%05d", i_);
            lfs3_mdir_t mdir;
            lfs3_tag_t tag;
            lfs3_data_t data;
            int err = lfs3_mtree_namelookup(&lfs3,
                    0, name, strlen(name),
                    &mdir, &tag, &data);
            assert(!err || err == LFS3_ERR_NOENT);
            if (!err) {
                assert(tag == LFS3_TAG_REG);
            }
            BENCH_STOP("namelookup");

            // measure mid lookups
            //
            // we use mid found by name lookup so we know mid is valid
            BENCH_START("lookup", i+1);
            lfs3_mtree_lookup(&lfs3, mdir.mid,
                    &mdir) => 0;
            BENCH_STOP("lookup");

            // measure traversal cost
            BENCH_START("traversal", i+1);
            lfs3_traversal_t t;
            lfs3_traversal_open(&lfs3, &t, 0) => 0;
            while (true) {
                struct lfs3_tinfo tinfo;
                int err = lfs3_traversal_read(&lfs3, &t,
                        &tinfo);
                assert(!err || err == LFS3_ERR_NOENT);
                if (err == LFS3_ERR_NOENT) {
                    break;
                }
            }
            lfs3_traversal_close(&lfs3, &t) => 0;
            BENCH_STOP("traversal");

            // measure disk usage
            lfs3_off_t count = 0;

            lfs3_traversal_open(&lfs3, &t, 0) => 0;
            while (true) {
                struct lfs3_tinfo tinfo;
                int err = lfs3_traversal_read(&lfs3, &t,
                        &tinfo);
                assert(!err || err == LFS3_ERR_NOENT);
                if (err == LFS3_ERR_NOENT) {
                    break;
                }

                count += 1;
            }
            lfs3_traversal_close(&lfs3, &t) => 0;

            BENCH_RESULT("usage", i+1,
                    (uintmax_t)count * CFG->block_size);
        }
    }

    lfs3_unmount(&lfs3) => 0;
'''
