# High-level read-throughput benchmarks


# these are common and can be overridden suite-wide
#
# note for bench_p26_litmus_many, CHUNK => file size, and SIZE = sum of
# all files
#
defines.SIZE = 32768
defines.CHUNK = 32
defines.SEED = 42

# simulated time, in nanoseconds, to run the test
defines.SIMTIME = '60000000000ULL' # 1 minute

# include common bench helpers
code = '''
#include "benches/bench_helpers.h"
'''


[cases.bench_p26_rt_linear]
code = '''
    #if defined(LFS3)
    lfs3_t lfs3;
    lfs3_format(&lfs3, LFS3_F_RDWR, CFG) => 0;
    lfs3_mount(&lfs3, LFS3_M_RDWR, CFG) => 0;
    #elif defined(LFS2)
    lfs2_t lfs2;
    lfs2_format(&lfs2, CFG_LFS2) => 0;
    lfs2_mount(&lfs2, CFG_LFS2) => 0;
    #elif defined(SPIFFS)
    spiffs spiffs;
    spiffs.user_data = CFG;
    uint8_t work_buffer[2*PAGE_SIZE];
    uint8_t fd_buffer[FD_SIZE];
    uint8_t pagecache_buffer[PAGECACHE_SIZE];
    // yes we need this mount
    SPIFFS_mount(&spiffs, (spiffs_config*)CFG_SPIFFS, work_buffer,
            fd_buffer, FD_SIZE,
            pagecache_buffer, PAGECACHE_SIZE,
            NULL) => SPIFFS_ERR_NOT_A_FS;
    SPIFFS_format(&spiffs) => 0;
    SPIFFS_mount(&spiffs, (spiffs_config*)CFG_SPIFFS, work_buffer,
            fd_buffer, FD_SIZE,
            pagecache_buffer, PAGECACHE_SIZE,
            NULL) => 0;
    #elif defined(YAFFS2)
    // note this implicitly zeros yaffs_dev
    struct yaffs_dev yaffs2 = {
        .driver_context = CFG,
        .param = CFG_YAFFS2->param,
        .drv = CFG_YAFFS2->drv,
    };
    yaffs_add_device(&yaffs2);
    yaffs_format("/", false, false, false) => 0;
    yaffs_mount("/") => 0;
    #endif
    uint32_t prng = SEED;

    // go ahead and make consistent to avoid lazy mount operations
    // messing with the benchmark
    #if defined(LFS3)
    lfs3_fs_mkconsistent(&lfs3) => 0;
    #elif defined(LFS2)
    lfs2_fs_mkconsistent(&lfs2) => 0;
    #elif defined(SPIFFS)
    SPIFFS_gc_quick(&spiffs, 0) => SPIFFS_ERR_NO_DELETED_BLOCKS;
    #elif defined(YAFFS2)
    yaffs_sync("/") => 0;
    #endif

    // create a file to read
    #if defined(LFS3)
    lfs3_file_t file;
    lfs3_file_open(&lfs3, &file, "bench_linear",
            LFS3_O_RDWR | LFS3_O_CREAT | LFS3_O_EXCL) => 0;
    for (lfs3_size_t i = 0; i < (SIZE+(CHUNK-1))/CHUNK; i++) {
        uint8_t wbuf[CHUNK];
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        lfs3_file_write(&lfs3, &file, wbuf, CHUNK) => CHUNK;
    }
    lfs3_file_close(&lfs3, &file) => 0;
    #elif defined(LFS2)
    lfs2_file_t file;
    lfs2_file_open(&lfs2, &file, "bench_linear",
            LFS2_O_RDWR | LFS2_O_CREAT | LFS2_O_EXCL) => 0;
    for (lfs3_size_t i = 0; i < (SIZE+(CHUNK-1))/CHUNK; i++) {
        uint8_t wbuf[CHUNK];
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        lfs2_file_write(&lfs2, &file, wbuf, CHUNK) => CHUNK;
    }
    lfs2_file_close(&lfs2, &file) => 0;
    #elif defined(SPIFFS)
    spiffs_file fd = SPIFFS_open(&spiffs, "bench_linear",
            SPIFFS_RDWR | SPIFFS_CREAT | SPIFFS_EXCL, 0777);
    assert(fd >= 0);
    for (lfs3_size_t i = 0; i < (SIZE+(CHUNK-1))/CHUNK; i++) {
        uint8_t wbuf[CHUNK];
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        SPIFFS_write(&spiffs, fd, wbuf, CHUNK) => CHUNK;
    }
    SPIFFS_close(&spiffs, fd) => 0;
    #elif defined(YAFFS2)
    int fd = yaffs_open("bench_linear",
            O_RDWR | O_CREAT | O_EXCL, 0777);
    assert(fd >= 0);
    for (lfs3_size_t i = 0; i < (SIZE+(CHUNK-1))/CHUNK; i++) {
        uint8_t wbuf[CHUNK];
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        yaffs_write(fd, wbuf, CHUNK) => CHUNK;
    }
    yaffs_close(fd) => 0;
    #endif

    // reset our timer
    bench_helpers_simreset(CFG);

    // open the file
    BENCH_START("read", 0);
    #if defined(LFS3)
    lfs3_file_open(&lfs3, &file, "bench_linear", LFS3_O_RDONLY) => 0;
    #elif defined(LFS2)
    lfs2_file_open(&lfs2, &file, "bench_linear", LFS2_O_RDONLY) => 0;
    #elif defined(SPIFFS)
    fd = SPIFFS_open(&spiffs, "bench_linear", SPIFFS_RDONLY, 0777);
    assert(fd >= 0);
    #elif defined(YAFFS2)
    fd = yaffs_open("bench_linear", O_RDONLY, 0777);
    #endif
    lfs3_off_t size = 0;
    uint64_t readed = 0;
    while (bench_helpers_simtime(CFG) < (uint64_t)SIMTIME) {
        // read from the file
        uint8_t rbuf[CHUNK];
        #if defined(LFS3)
        lfs3_file_read(&lfs3, &file, rbuf, CHUNK) => CHUNK;
        #elif defined(LFS2)
        lfs2_file_read(&lfs2, &file, rbuf, CHUNK) => CHUNK;
        #elif defined(SPIFFS)
        SPIFFS_read(&spiffs, fd, rbuf, CHUNK) => CHUNK;
        #elif defined(YAFFS2)
        yaffs_read(fd, rbuf, CHUNK) => CHUNK;
        #endif
        size += CHUNK;
        readed += CHUNK;

        // rewind if we reach the end
        if (size >= SIZE) {
            #if defined(LFS3)
            lfs3_file_rewind(&lfs3, &file) => 0;
            #elif defined(LFS2)
            lfs2_file_rewind(&lfs2, &file) => 0;
            #elif defined(SPIFFS)
            SPIFFS_lseek(&spiffs, fd, 0, SPIFFS_SEEK_SET) => 0;
            #elif defined(YAFFS2)
            yaffs_lseek(fd, 0, SEEK_SET) => 0;
            #endif
            size = 0;
        }

        // bail if we get stuck
        if (bench_helpers_simstuck(CFG, readed)) {
            return;
        }
    }
    #if defined(LFS3)
    lfs3_file_close(&lfs3, &file) => 0;
    #elif defined(LFS2)
    lfs2_file_close(&lfs2, &file) => 0;
    #elif defined(SPIFFS)
    SPIFFS_close(&spiffs, fd) => 0;
    #elif defined(YAFFS2)
    yaffs_close(fd) => 0;
    #endif
    BENCH_STOP("read");

    // it's a bit awkward, but this reports the amount read to
    // result scripts
    // TODO we should really move n to BENCH_STOP
    BENCH_START("read", readed);
    BENCH_STOP("read");

    #if defined(LFS3)
    lfs3_unmount(&lfs3) => 0;
    #elif defined(LFS2)
    lfs2_unmount(&lfs2) => 0;
    #elif defined(SPIFFS)
    SPIFFS_unmount(&spiffs);
    #elif defined(YAFFS2)
    yaffs_unmount("/") => 0;
    yaffs_remove_device(&yaffs2);
    #endif
'''

[cases.bench_p26_rt_random]
code = '''
    #if defined(LFS3)
    lfs3_t lfs3;
    lfs3_format(&lfs3, LFS3_F_RDWR, CFG) => 0;
    lfs3_mount(&lfs3, LFS3_M_RDWR, CFG) => 0;
    #elif defined(LFS2)
    lfs2_t lfs2;
    lfs2_format(&lfs2, CFG_LFS2) => 0;
    lfs2_mount(&lfs2, CFG_LFS2) => 0;
    #elif defined(SPIFFS)
    spiffs spiffs;
    spiffs.user_data = CFG;
    uint8_t work_buffer[2*PAGE_SIZE];
    uint8_t fd_buffer[FD_SIZE];
    uint8_t pagecache_buffer[PAGECACHE_SIZE];
    // yes we need this mount
    SPIFFS_mount(&spiffs, (spiffs_config*)CFG_SPIFFS, work_buffer,
            fd_buffer, FD_SIZE,
            pagecache_buffer, PAGECACHE_SIZE,
            NULL) => SPIFFS_ERR_NOT_A_FS;
    SPIFFS_format(&spiffs) => 0;
    SPIFFS_mount(&spiffs, (spiffs_config*)CFG_SPIFFS, work_buffer,
            fd_buffer, FD_SIZE,
            pagecache_buffer, PAGECACHE_SIZE,
            NULL) => 0;
    #elif defined(YAFFS2)
    // note this implicitly zeros yaffs_dev
    struct yaffs_dev yaffs2 = {
        .driver_context = CFG,
        .param = CFG_YAFFS2->param,
        .drv = CFG_YAFFS2->drv,
    };
    yaffs_add_device(&yaffs2);
    yaffs_format("/", false, false, false) => 0;
    yaffs_mount("/") => 0;
    #endif
    uint32_t prng = SEED;

    // go ahead and make consistent to avoid lazy mount operations
    // messing with the benchmark
    #if defined(LFS3)
    lfs3_fs_mkconsistent(&lfs3) => 0;
    #elif defined(LFS2)
    lfs2_fs_mkconsistent(&lfs2) => 0;
    #elif defined(SPIFFS)
    SPIFFS_gc_quick(&spiffs, 0) => SPIFFS_ERR_NO_DELETED_BLOCKS;
    #elif defined(YAFFS2)
    yaffs_sync("/") => 0;
    #endif

    // create a file to read
    #if defined(LFS3)
    lfs3_file_t file;
    lfs3_file_open(&lfs3, &file, "bench_random",
            LFS3_O_RDWR | LFS3_O_CREAT | LFS3_O_EXCL) => 0;
    for (lfs3_size_t i = 0; i < (SIZE+(CHUNK-1))/CHUNK; i++) {
        uint8_t wbuf[CHUNK];
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        lfs3_file_write(&lfs3, &file, wbuf, CHUNK) => CHUNK;
    }
    lfs3_file_close(&lfs3, &file) => 0;
    #elif defined(LFS2)
    lfs2_file_t file;
    lfs2_file_open(&lfs2, &file, "bench_random",
            LFS2_O_RDWR | LFS2_O_CREAT | LFS2_O_EXCL) => 0;
    for (lfs3_size_t i = 0; i < (SIZE+(CHUNK-1))/CHUNK; i++) {
        uint8_t wbuf[CHUNK];
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        lfs2_file_write(&lfs2, &file, wbuf, CHUNK) => CHUNK;
    }
    lfs2_file_close(&lfs2, &file) => 0;
    #elif defined(SPIFFS)
    spiffs_file fd = SPIFFS_open(&spiffs, "bench_random",
            SPIFFS_RDWR | SPIFFS_CREAT | SPIFFS_EXCL, 0777);
    assert(fd >= 0);
    for (lfs3_size_t i = 0; i < (SIZE+(CHUNK-1))/CHUNK; i++) {
        uint8_t wbuf[CHUNK];
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        SPIFFS_write(&spiffs, fd, wbuf, CHUNK) => CHUNK;
    }
    SPIFFS_close(&spiffs, fd) => 0;
    #elif defined(YAFFS2)
    int fd = yaffs_open("bench_random",
            O_RDWR | O_CREAT | O_EXCL, 0777);
    assert(fd >= 0);
    for (lfs3_size_t i = 0; i < (SIZE+(CHUNK-1))/CHUNK; i++) {
        uint8_t wbuf[CHUNK];
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        yaffs_write(fd, wbuf, CHUNK) => CHUNK;
    }
    yaffs_close(fd) => 0;
    #endif

    // reset our timer
    bench_helpers_simreset(CFG);

    // open the file
    BENCH_START("read", 0);
    #if defined(LFS3)
    lfs3_file_open(&lfs3, &file, "bench_random", LFS3_O_RDONLY) => 0;
    #elif defined(LFS2)
    lfs2_file_open(&lfs2, &file, "bench_random", LFS2_O_RDONLY) => 0;
    #elif defined(SPIFFS)
    fd = SPIFFS_open(&spiffs, "bench_random", SPIFFS_RDONLY, 0777);
    assert(fd >= 0);
    #elif defined(YAFFS2)
    fd = yaffs_open("bench_random", O_RDONLY, 0777);
    #endif
    uint64_t readed = 0;
    while (bench_helpers_simtime(CFG) < (uint64_t)SIMTIME) {
        // seek to a random location
        lfs3_off_t pos = BENCH_PRNG(&prng) % SIZE;
        #if defined(LFS3)
        lfs3_file_seek(&lfs3, &file, pos, LFS3_SEEK_SET) => pos;
        #elif defined(LFS2)
        lfs2_file_seek(&lfs2, &file, pos, LFS2_SEEK_SET) => pos;
        #elif defined(SPIFFS)
        SPIFFS_lseek(&spiffs, fd, pos, SPIFFS_SEEK_SET) => pos;
        #elif defined(YAFFS2)
        yaffs_lseek(fd, pos, SEEK_SET) => pos;
        #endif

        // read from the file
        uint8_t rbuf[CHUNK];
        #if defined(LFS3)
        lfs3_ssize_t d = lfs3_file_read(&lfs3, &file, rbuf, CHUNK);
        assert(d <= CHUNK);
        #elif defined(LFS2)
        lfs2_ssize_t d = lfs2_file_read(&lfs2, &file, rbuf, CHUNK);
        assert(d <= CHUNK);
        #elif defined(SPIFFS)
        s32_t d = SPIFFS_read(&spiffs, fd, rbuf, CHUNK);
        assert(d <= CHUNK);
        #elif defined(YAFFS2)
        ssize_t d = yaffs_read(fd, rbuf, CHUNK);
        assert(d <= CHUNK);
        #endif
        readed += CHUNK;

        // bail if we get stuck
        if (bench_helpers_simstuck(CFG, readed)) {
            return;
        }
    }
    #if defined(LFS3)
    lfs3_file_close(&lfs3, &file) => 0;
    #elif defined(LFS2)
    lfs2_file_close(&lfs2, &file) => 0;
    #elif defined(SPIFFS)
    SPIFFS_close(&spiffs, fd) => 0;
    #elif defined(YAFFS2)
    yaffs_close(fd) => 0;
    #endif
    BENCH_STOP("read");

    // it's a bit awkward, but this reports the amount read to
    // result scripts
    // TODO we should really move n to BENCH_STOP
    BENCH_START("read", readed);
    BENCH_STOP("read");

    #if defined(LFS3)
    lfs3_unmount(&lfs3) => 0;
    #elif defined(LFS2)
    lfs2_unmount(&lfs2) => 0;
    #elif defined(SPIFFS)
    SPIFFS_unmount(&spiffs);
    #elif defined(YAFFS2)
    yaffs_unmount("/") => 0;
    yaffs_remove_device(&yaffs2);
    #endif
'''

[cases.bench_p26_rt_many]
if = [
    # spiffs simply doesn't scale well enough to create this many files
    # before we start reading
    'BENCH_IFDEF_SPIFFS(SIZE < 128*1024, true)',
    # and surprisingly this was an issue for yaffs2 as well! but not on
    # disk! the internal RAM-backed linked-list of on-disk files grows
    # O(n), we aren't benchmarking this but it becomes a problem for
    # actually running this bench
    'BENCH_IFDEF_YAFFS2(SIZE < 128*1024, true)',
]
code = '''
    #if defined(LFS3)
    lfs3_t lfs3;
    lfs3_format(&lfs3, LFS3_F_RDWR, CFG) => 0;
    lfs3_mount(&lfs3, LFS3_M_RDWR, CFG) => 0;
    #elif defined(LFS2)
    lfs2_t lfs2;
    lfs2_format(&lfs2, CFG_LFS2) => 0;
    lfs2_mount(&lfs2, CFG_LFS2) => 0;
    #elif defined(SPIFFS)
    spiffs spiffs;
    spiffs.user_data = CFG;
    uint8_t work_buffer[2*PAGE_SIZE];
    uint8_t fd_buffer[FD_SIZE];
    uint8_t pagecache_buffer[PAGECACHE_SIZE];
    // yes we need this mount
    SPIFFS_mount(&spiffs, (spiffs_config*)CFG_SPIFFS, work_buffer,
            fd_buffer, FD_SIZE,
            pagecache_buffer, PAGECACHE_SIZE,
            NULL) => SPIFFS_ERR_NOT_A_FS;
    SPIFFS_format(&spiffs) => 0;
    SPIFFS_mount(&spiffs, (spiffs_config*)CFG_SPIFFS, work_buffer,
            fd_buffer, FD_SIZE,
            pagecache_buffer, PAGECACHE_SIZE,
            NULL) => 0;
    #elif defined(YAFFS2)
    // note this implicitly zeros yaffs_dev
    struct yaffs_dev yaffs2 = {
        .driver_context = CFG,
        .param = CFG_YAFFS2->param,
        .drv = CFG_YAFFS2->drv,
    };
    yaffs_add_device(&yaffs2);
    yaffs_format("/", false, false, false) => 0;
    yaffs_mount("/") => 0;
    #endif
    uint32_t prng = SEED;

    // go ahead and make consistent to avoid lazy mount operations
    // messing with the benchmark
    #if defined(LFS3)
    lfs3_fs_mkconsistent(&lfs3) => 0;
    #elif defined(LFS2)
    lfs2_fs_mkconsistent(&lfs2) => 0;
    #elif defined(SPIFFS)
    SPIFFS_gc_quick(&spiffs, 0) => SPIFFS_ERR_NO_DELETED_BLOCKS;
    #elif defined(YAFFS2)
    yaffs_sync("/") => 0;
    #endif

    // create files to read
    #if defined(LFS3)
    for (lfs3_size_t i = 0; i < (SIZE+(CHUNK-1))/CHUNK; i++) {
        char name[256];
        sprintf(name, "bench_%08x", i);
        lfs3_file_t file;
        lfs3_file_open(&lfs3, &file, name,
                LFS3_O_RDWR | LFS3_O_CREAT | LFS3_O_EXCL) => 0;
        uint8_t wbuf[CHUNK];
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        lfs3_file_write(&lfs3, &file, wbuf, CHUNK) => CHUNK;
        lfs3_file_close(&lfs3, &file) => 0;
    }
    #elif defined(LFS2)
    for (lfs3_size_t i = 0; i < (SIZE+(CHUNK-1))/CHUNK; i++) {
        char name[256];
        sprintf(name, "bench_%08x", i);
        lfs2_file_t file;
        lfs2_file_open(&lfs2, &file, name,
                LFS2_O_RDWR | LFS2_O_CREAT | LFS2_O_EXCL) => 0;
        uint8_t wbuf[CHUNK];
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        lfs2_file_write(&lfs2, &file, wbuf, CHUNK) => CHUNK;
        lfs2_file_close(&lfs2, &file) => 0;
    }
    #elif defined(SPIFFS)
    for (lfs3_size_t i = 0; i < (SIZE+(CHUNK-1))/CHUNK; i++) {
        char name[256];
        sprintf(name, "bench_%08x", i);
        spiffs_file fd = SPIFFS_open(&spiffs, name,
                SPIFFS_RDWR | SPIFFS_CREAT | SPIFFS_EXCL, 0777);
        assert(fd >= 0);
        uint8_t wbuf[CHUNK];
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        SPIFFS_write(&spiffs, fd, wbuf, CHUNK) => CHUNK;
        SPIFFS_close(&spiffs, fd) => 0;
    }
    #elif defined(YAFFS2)
    for (lfs3_size_t i = 0; i < (SIZE+(CHUNK-1))/CHUNK; i++) {
        char name[256];
        sprintf(name, "bench_%08x", i);
        int fd = yaffs_open(name, O_RDWR | O_CREAT | O_EXCL, 0777);
        assert(fd >= 0);
        uint8_t wbuf[CHUNK];
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        yaffs_write(fd, wbuf, CHUNK) => CHUNK;
        yaffs_close(fd) => 0;
    }
    #endif

    // reset our timer
    bench_helpers_simreset(CFG);

    // open the files
    BENCH_START("read", 0);
    uint64_t readed = 0;
    while (bench_helpers_simtime(CFG) < (uint64_t)SIMTIME) {
        // choose a random filename
        lfs3_off_t pos = BENCH_PRNG(&prng) % ((SIZE+(CHUNK-1))/CHUNK);
        char name[256];
        sprintf(name, "bench_%08x", pos);

        // read the file
        //
        // note file == CHUNK here, the sum of all files should add up
        // roughly to the benchmark SIZE
        uint8_t rbuf[CHUNK];
        #if defined(LFS3)
        lfs3_file_t file;
        lfs3_file_open(&lfs3, &file, name, LFS3_O_RDONLY) => 0;
        lfs3_file_read(&lfs3, &file, rbuf, CHUNK) => CHUNK;
        lfs3_file_close(&lfs3, &file) => 0;
        #elif defined(LFS2)
        lfs2_file_t file;
        lfs2_file_open(&lfs2, &file, name, LFS2_O_RDONLY) => 0;
        lfs2_file_read(&lfs2, &file, rbuf, CHUNK) => CHUNK;
        lfs2_file_close(&lfs2, &file) => 0;
        #elif defined(SPIFFS)
        spiffs_file fd = SPIFFS_open(&spiffs, name, SPIFFS_RDONLY, 0777);
        assert(fd >= 0);
        SPIFFS_read(&spiffs, fd, rbuf, CHUNK) => CHUNK;
        SPIFFS_close(&spiffs, fd) => 0;
        #elif defined(YAFFS2)
        int fd = yaffs_open(name, O_RDONLY, 0777);
        assert(fd >= 0);
        yaffs_read(fd, rbuf, CHUNK) => CHUNK;
        yaffs_close(fd) => 0;
        #endif

        readed += CHUNK;

        // bail if we get stuck
        if (bench_helpers_simstuck(CFG, readed)) {
            return;
        }
    }
    BENCH_STOP("read");

    // it's a bit awkward, but this reports the amount read to
    // result scripts
    // TODO we should really move n to BENCH_STOP
    BENCH_START("read", readed);
    BENCH_STOP("read");

    #if defined(LFS3)
    lfs3_unmount(&lfs3) => 0;
    #elif defined(LFS2)
    lfs2_unmount(&lfs2) => 0;
    #elif defined(SPIFFS)
    SPIFFS_unmount(&spiffs);
    #elif defined(YAFFS2)
    yaffs_unmount("/") => 0;
    yaffs_remove_device(&yaffs2);
    #endif
'''
